### ISSUE TITLE
Method not found: 'Boolean SpiceSharp.Circuits.Entity.SetParameter(System.String, Double, System.Collections.Generic.IEqualityComparer`1)'

### ISSUE THREAD

**Issue by user4githvb** [SpiceSharp/SpiceSharpParser#104]
I have issue with diode example (from tutorial):

        var netlist = string.Join(Environment.NewLine,
            "Diode circuit",
            "D1 OUT 0 1N914",
            "V1 OUT 0 0",
            ".model 1N914 D(Is=2.52e-9 Rs=0.568 N=1.752 Cjo=4e-12 M=0.4 tt=20e-9)",
            ".DC V1 -1 1 10e-3",
            ".SAVE i(V1)",
            ".END");

        // Parsing part - SpiceSharpParser
        var parser = new SpiceParser();
        var parseResult = parser.ParseNetlist(netlist);
        var spiceSharpModel = parseResult.SpiceSharpModel;

Method not found: 'Boolean SpiceSharp.Circuits.Entity.SetParameter(System.String, Double, System.Collections.Generic.IEqualityComparer`1)'

**Comment by user4githvb** [comment]
Solved - It occurs that SpiceSharp Parser nuget includes a version of SpiceSharp that is older then SpiceSparp standalone nuget that I also installed - even before SpiceSharp Parser.
Newest version of SpiceSparp is in conflict with Parser that required older package.

**Comment by marcin-golebiowski** [comment]
@user4githvb  Should be fine now. New version of Spice#.Parser has been published.

**Comment by user4githvb** [comment]
Now parser works fine - thank You thank You very much.

**Comment by marcin-golebiowski** [comment]
@user4githvb If you have any problems, feel free to write e-mail to me or write here.
