### ISSUE TITLE
Valid Component Names

### ISSUE THREAD

**Issue by ToddThomson** [SpiceSharp/SpiceSharpParser#140]
The Netlist lexer properly allows for components to have single letter word names. Is this OK from a grammar point of view?
```
R 1 2 2K ; No resister identifier
```

**Comment by marcin-golebiowski** [comment]
@ToddThomson  Let me think about it. What is your opinion about it?

**Comment by ToddThomson** [comment]
@marcin-golebiowski Spice Netlist grammar is not standardized. My initial thought was that a component should have an identifier. I'll do a bit of research on it...

**Comment by ToddThomson** [comment]
@marcin-golebiowski Component instance names can be single letter.

**Comment by ToddThomson** [comment]
No changes necessary as single letter component identifiers are grammatically correct.
