### ISSUE TITLE
.PRINT/.PLOT statements without specifying the simulation type

### ISSUE THREAD

**Issue by svenboulanger** [SpiceSharp/SpiceSharpParser#88]
Currently these statements need the simulation type to be specified. Most simulators don't require this.

```
.PRINT TRAN V(out)
```
would become just

```
.PRINT V(out)
```

The statement would cause all simulations in the netlist to export `V(out)`. If a simulation can't export it then the simulator will usually silently ignore it for that simulation.

If no simulations can export `V(out)`, then I believe a warning should be in order.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  It's implemented in latest version of SpiceShaprParser. Please check it.

**Comment by marcin-golebiowski** [comment]
@svenboulanger  Can I close an issue ?

**Comment by svenboulanger** [comment]
Yeah sure!
